import os

TEMPORAL_HOST = os.getenv("TEMPORAL_HOST", "localhost:7233")
OPS_SENTINEL_TASK_QUEUE = os.getenv("OPS_SENTINEL_TASK_QUEUE", "ops-sentinel-task-queue")

NEBIUS_API_KEY = os.getenv("NEBIUS_API_KEY")
NEBIUS_MODEL_ID = os.getenv("NEBIUS_MODEL_ID", "nebius/deepseek-ai/DeepSeek-V3-0324")

DOCKER_HOST = os.getenv("DOCKER_HOST", "unix:///var/run/docker.sock")
DOCKER_TIMEOUT = int(os.getenv("DOCKER_TIMEOUT", "30"))

STATUS_CHECK_TIMEOUT = 10
HEALTH_CHECK_TIMEOUT = 15
LOG_RETRIEVAL_TIMEOUT = 10
RESTART_TIMEOUT = 30
AI_ORCHESTRATOR_TIMEOUT = 15

CPU_THRESHOLD_PERCENT = 90.0
MEMORY_THRESHOLD_PERCENT = 90.0
RESTART_COUNT_THRESHOLD = 5

TASK_QUEUE = OPS_SENTINEL_TASK_QUEUE
